### ISSUE TITLE
Lot of repeating UnhandledPromiseRejectionWarning messages in log

### ISSUE THREAD

**Issue by revog** [emptygalaxy/homebridge-comfoair#1]
Hello

Just installed your great plugin for Homebridge of ComfoAir. I do get a lot of UnhandledPromiseRejectionWarning messages in the log files. 
Despite of this, the plugin seems to work as I do get values like temperature and fan level and so on.

As I'm not (yet) really familiar with NodeJS do you know what the cause could be?

Would be great to get this (may irrelevant?) messages away in the logs.

`[6/21/2020, 9:54:02 PM] [ComfoAir 350 Luxe] Connected to Comfoair
[6/21/2020, 9:54:02 PM] [ComfoAir 350 Luxe] 
[6/21/2020, 9:54:02 PM] [ComfoAir 350 Luxe] Interval update
[6/21/2020, 9:54:02 PM] [ComfoAir 350 Luxe] Queue size of 30 exceeded. Command "getVentilationLevel" discarded.
[6/21/2020, 9:54:02 PM] [ComfoAir 350 Luxe] Power=false
[6/21/2020, 9:54:02 PM] [ComfoAir 350 Luxe] Speed: 1
[6/21/2020, 9:54:02 PM] [ComfoAir 350 Luxe] Queue size of 30 exceeded. Command "getOperatingHours" discarded.
[6/21/2020, 9:54:02 PM] [ComfoAir 350 Luxe] filterOperatingHours=175
[6/21/2020, 9:54:02 PM] [ComfoAir 350 Luxe] FilterLifeLevel=583
[6/21/2020, 9:54:02 PM] [ComfoAir 350 Luxe] Queue size of 30 exceeded. Command "getFaults" discarded.
[6/21/2020, 9:54:02 PM] [ComfoAir 350 Luxe] replaceFilter=false
(node:5281) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at /homebridge/node_modules/homebridge-comfoair/index.js:898:81
    at returnData (/homebridge/node_modules/homebridge-comfoair/node_modules/comfoair/Comfoair.js:135:50)
    at ComfoairStream.dataHandler (/homebridge/node_modules/homebridge-comfoair/node_modules/comfoair/Comfoair.js:166:17)
    at ComfoairStream.emit (events.js:315:20)
    at ProtocolParser.<anonymous> (/homebridge/node_modules/homebridge-comfoair/node_modules/comfoair/ComfoairStream.js:34:18)
    at ProtocolParser.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at ProtocolParser.Readable.push (_stream_readable.js:212:10)
    at ProtocolParser.Transform.push (_stream_transform.js:152:32)
(node:5281) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 59)
[6/21/2020, 9:54:07 PM] [ComfoAir 350 Luxe] 
[6/21/2020, 9:54:07 PM] [ComfoAir 350 Luxe] Interval update
[6/21/2020, 9:54:07 PM] [ComfoAir 350 Luxe] Queue size of 30 exceeded. Command "getVentilationLevel" discarded.
[6/21/2020, 9:54:07 PM] [ComfoAir 350 Luxe] Power=false
[6/21/2020, 9:54:07 PM] [ComfoAir 350 Luxe] Speed: 1
[6/21/2020, 9:54:07 PM] [ComfoAir 350 Luxe] Queue size of 30 exceeded. Command "getOperatingHours" discarded.
[6/21/2020, 9:54:07 PM] [ComfoAir 350 Luxe] filterOperatingHours=175
[6/21/2020, 9:54:07 PM] [ComfoAir 350 Luxe] FilterLifeLevel=583
[6/21/2020, 9:54:07 PM] [ComfoAir 350 Luxe] Queue size of 30 exceeded. Command "getFaults" discarded.
[6/21/2020, 9:54:07 PM] [ComfoAir 350 Luxe] replaceFilter=false
[6/21/2020, 9:54:08 PM] [ComfoAir 350 Luxe] Comfoair error: Queue timeout of 5s exceeded. Restarting Comfoair module.
[6/21/2020, 9:54:08 PM] [ComfoAir 350 Luxe] Disconnected from Comfoair`

Regards revog

**Comment by revog** [comment]
Issue seems to be solved since 0.3.2. Many thanks to Nick Timman's commit https://github.com/emptygalaxy/homebridge-comfoair/commit/8f4d5900d99d6b403f66d94ed4c38f080fe113f1. Thumbs up!

**Comment by emptygalaxy** [comment]
Thanks for letting me know, after a few updates I didn't check the logs anymore.
Anyways, I was already working on rewriting the plugin in Typescript for stability and this fixed the unhandled promise rejection too.
Good to hear other people are making use of it too!
