### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gbbr** [emptygalaxy/homebridge-comfoair#18]
Are there any plans to add some basic documentation? I'm trying to set this up.

* I have Homebridge installed on my laptop
* ComfoConnect LAN C (controlling a ComfoAir Q350 unit) is connected to the network switch and works via the app.

How can I get this working with Homebridge? I did figure out that its using [node-comfoair](https://github.com/coolchip/node-comfoair), but not sure what to enter for the "Port" section. I just know the IP of ComfoConnect LAN C.

**Comment by emptygalaxy** [comment]
Some documentation would be in place, I'll see if I can set that up later. 
This plugin is only for connecting Comfoair over its serial port and not supporting network devices. If node-comfoair adds support then I can update the homebridge plugin accordingly.

**Comment by gbbr** [comment]
Ok, I see. Thanks for clarifying. A small README saying only that I think would be of great help to most people arriving here.

**Comment by CWiedermann** [comment]
Hi

node-comfoair does not support the ComfoConnect LAN device, but node-comfoairq does!
https://github.com/herrJones/node-comfoairq

Any chance you would include this in your homebridge plugin?

**Comment by MikeMighty** [comment]
Oke, Been on it for days now and I really cant figure out the port. What string should i put there? The Comfoair is connectend with the LAN C box. I am cleary using the wrong port at the moment as Homebridge as a whole starts to error. Warnings saying this plugin is slowing down the system and this error:

[30/06/2023, 11:17:00] Error: Queue timeout of 5s exceeded. Restarting Comfoair module.
    at Queue.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/comfoair@1.0.6/node_modules/comfoair/Comfoair.js:27:32)
    at Queue.emit (node:events:513:28)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/.pnpm/queue@6.0.2/node_modules/queue/index.js:130:14)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)

Is there a simple way to get the port string/ value? Or is this just over my head. Then I ll give up :)
