### ISSUE TITLE
plugin generated a warning from the characteristic 'Filter Life Level'

### ISSUE THREAD

**Issue by revog** [emptygalaxy/homebridge-comfoair#6]
Hello

Since I updated my homebridge container to the newest version (oznu/homebridge) I regularly get the following errors:
`[3/8/2021, 8:08:26 PM] [homebridge-comfoair] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic was supplied illegal value: number 247 exceeded maximum of 100. See https://git.io/JtMGR for more info.`
or
`[3/8/2021, 8:11:22 PM] [homebridge-comfoair] This plugin generated a warning from the characteristic 'S2W2': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.`

As stated the first one is related to the filter life level I'd say. So when using the filter reset function the following trace is printed and homebridge plugin gets restarted:

```
error: unhandled rejection: TypeError: callback is not a function
    at ComfoAirAccessory.<anonymous> (/homebridge/node_modules/homebridge-comfoair/src/FilterHandler.ts:95:13)
    at ComfoAirAccessory.handleResetFilter (/homebridge/node_modules/homebridge-comfoair/src/ComfoAirAccessory.ts:419:22)
    at /homebridge/node_modules/homebridge-comfoair/src/ComfoAirAccessory.ts:389:26
    at returnData (/homebridge/node_modules/homebridge-comfoair/node_modules/comfoair/Comfoair.js:135:50)
    at ComfoairStream.dataHandler (/homebridge/node_modules/homebridge-comfoair/node_modules/comfoair/Comfoair.js:166:17)
    at ComfoairStream.emit (events.js:315:20)
    at ProtocolParser.<anonymous> (/homebridge/node_modules/homebridge-comfoair/node_modules/comfoair/ComfoairStream.js:34:18)
    at ProtocolParser.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
[3/8/2021, 8:08:35 PM] Error: Queue timeout of 5s exceeded. Restarting Comfoair module.
    at Queue.<anonymous> (/homebridge/node_modules/homebridge-comfoair/node_modules/comfoair/Comfoair.js:26:32)
    at Queue.emit (events.js:315:20)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-comfoair/node_modules/queue/index.js:130:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

Don't know the exact cause of this. 

Version information:
Node.js Version v14.16.0
Npm Versionv 6.14.11
Comfoair-Plugin 0.3.2 & 0.3.3

Let me know if you need further information.

Regards revog

**Comment by emptygalaxy** [comment]
The cause is related to the max filter life time. I'm not sure what the maximum value should be so it's configurable in the config (maxFilterLife). It then calculates the characteristic value as filter life time / max filter life time. The characteristic however should be a number between 0 and 100, but since the max filter life is not known, it probably exceeds that 100. You can increase the max filter life time, or wait until I've issued an update to this plugin to fix this. I was working on refactoring some key components so I'll need to fix that up first before publishing.
